name: DevOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        working-directory: devops-dia6/app
        run: |
          pip install -r requirements.txt

      - name: Comprobar sintaxis Python
        working-directory: devops-dia6/app
        run: |
          python -m py_compile app.py

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: |
          docker build \
            -t proyecto-devops:v1 \
            -f devops-dia6/docker/Dockerfile \
            .
